export const LogFields = {
  ID: "id",
  DRIVER: "driver",
  DEVICE: "device",
  VEHICLE: "vehicle",
  EVENT_TYPE: "event_type",
  EVENT_CODE: "event_code",
  EVENT_DATE: "event_date",
  EVENT_TIME: "event_time",
  COMMENT_TEXT: "comment_text",
  LOCATION_DESCRIPTION: "location_description",
  CERTIFIED_DATE: "certified_date",
  RECORD_STATUS: "record_status",
  RECORD_ORIGIN: "record_origin",
  ACCUMULATED_MILES: "accumulated_miles",
  ACCUMULATED_HOURS: "accumulated_hours",
  LATITUDE: "latitude",
  LONGITUDE: "longitude",
  DISTANCE_LAST_COORDINATES: "distance_last_coordinates",
  MALFUNCTION_STATUS: "malfunction_status",
  DIAGNOSTIC_INDICATOR: "diagnostic_indicator",
  TOTAL_MILES: "total_miles",
  TOTAL_HOURS: "total_hours",
  DIAGNOSTIC_CODE: "diagnostic_code",
  TRAILER_NUMBER: "trailer_number",
  SHIPPING_DOCUMENT_NUMBER: "shipping_document_number",
};

export const LogLoginFields = {
  ID: "id",
  DRIVER: "driver",
  DEVICE: "device",
  VEHICLE: "vehicle",
  EVENT_TYPE: "event_type",
  EVENT_CODE: "event_code",
  EVENT_DATE: "event_date",
  EVENT_TIME: "event_time",
  TOTAL_MILES: "total_miles",
  TOTAL_HOURS: "total_hours",
};

export const LogAnnotationFields = {
  ID: "id",
  DRIVER: "driver",
  DEVICE: "device",
  VEHICLE: "vehicle",
  EVENT_TYPE: "event_type",
  EVENT_CODE: "event_code",
  EVENT_DATE: "event_date",
  EVENT_TIME: "event_time",
  COMMENT_TEXT: "comment_text",
  LOCATION_DESCRIPTION: "location_description",
};

export const LogLogFields = {
  ID: "id",
  DRIVER: "driver",
  DEVICE: "device",
  VEHICLE: "vehicle",
  EVENT_TYPE: "event_type",
  EVENT_CODE: "event_code",
  EVENT_DATE: "event_date",
  EVENT_TIME: "event_time",
  RECORD_STATUS: "record_status",
  RECORD_ORIGIN: "record_origin",
  ACCUMULATED_MILES: "accumulated_miles",
  ACCUMULATED_HOURS: "accumulated_hours",
  LATITUDE: "latitude",
  LONGITUDE: "longitude",
  DISTANCE_LAST_COORDINATES: "distance_last_coordinates",
  MALFUNCTION_STATUS: "malfunction_status",
  DIAGNOSTIC_INDICATOR: "diagnostic_indicator",
};

export const LogCertificationFields = {
  ID: "id",
  DRIVER: "driver",
  DEVICE: "device",
  VEHICLE: "vehicle",
  EVENT_TYPE: "event_type",
  EVENT_CODE: "event_code",
  EVENT_DATE: "event_date",
  EVENT_TIME: "event_time",
  CERTIFIED_DATE: "certified_date",
};

export const LogMalFunctionFields = {
  ID: "id",
  DRIVER: "driver",
  DEVICE: "device",
  VEHICLE: "vehicle",
  EVENT_TYPE: "event_type",
  EVENT_CODE: "event_code",
  EVENT_DATE: "event_date",
  EVENT_TIME: "event_time",
  TOTAL_MILES: "total_miles",
  TOTAL_HOURS: "total_hours",
  DIAGNOSTIC_CODE: "diagnostic_code",
};

export const LogPowerFields = {
  ID: "id",
  DRIVER: "driver",
  DEVICE: "device",
  VEHICLE: "vehicle",
  EVENT_TYPE: "event_type",
  EVENT_CODE: "event_code",
  EVENT_DATE: "event_date",
  EVENT_TIME: "event_time",
  LATITUDE: "latitude",
  LONGITUDE: "longitude",
  TOTAL_MILES: "total_miles",
  TOTAL_HOURS: "total_hours",
  TRAILER_NUMBER: "trailer_number",
  SHIPPING_DOCUMENT_NUMBER: "shipping_document_number",
};
