export const carriers = [
  {
    id: 0,
    name: "Carrier 0",
    dotNumber: "dot 0",
    carrierId: "Carrier id 0",
    timeZone: "time zone 0",
    status: "Active",
  },
  {
    id: 1,
    name: "Carrier 1",
    dotNumber: "dot 1",
    carrierId: "Carrier id 1",
    timeZone: "time zone 1",
    status: "Active",
  },
  {
    id: 2,
    name: "Carrier 2",
    dotNumber: "dot 2",
    carrierId: "Carrier id 2",
    timeZone: "time zone 2",
    status: "Active",
  },
  {
    id: 3,
    name: "Carrier 3",
    dotNumber: "dot 3",
    carrierId: "Carrier id 3",
    timeZone: "time zone 3",
    status: "Active",
  },
  {
    id: 4,
    name: "Carrier 4",
    dotNumber: "dot 4",
    carrierId: "Carrier id 4",
    timeZone: "time zone 4",
    status: "Active",
  },
  {
    id: 5,
    name: "Carrier 5",
    dotNumber: "dot 5",
    carrierId: "Carrier id 5",
    timeZone: "time zone 5",
    status: "Active",
  },
  {
    id: 6,
    name: "Carrier 6",
    dotNumber: "dot 6",
    carrierId: "Carrier id 6",
    timeZone: "time zone 6",
    status: "Active",
  },
  {
    id: 7,
    name: "Carrier 7",
    dotNumber: "dot 7",
    carrierId: "Carrier id 7",
    timeZone: "time zone 7",
    status: "Active",
  },
  {
    id: 8,
    name: "Carrier 8",
    dotNumber: "dot 8",
    carrierId: "Carrier id 8",
    timeZone: "time zone 8",
    status: "Active",
  },
  {
    id: 9,
    name: "Carrier 9",
    dotNumber: "dot 9",
    carrierId: "Carrier id 9",
    timeZone: "time zone 9",
    status: "Active",
  },
];
