import { InputType } from "../../../../constants/inputs";
import { generateArrayOfYears } from "../../../../hooks/utils";
import {
  VALIDATION_RULES,
  validate,
  VALIDATION_TYPE,
  getValidation,
} from "../../../../utils/validation";
import {
  carrierStatusOptions,
  CarrierField,
  carrierCheckboxGroup,
  carrierData,
  VehicleField,
} from "../constant";

const { ALPHABETICAL, REQUIRED, MIN, MAX, NUMERIC, PASSWORD, EMAIL, NAME } =
  VALIDATION_TYPE;

export const LogFields = {
  type: InputType.MULTI,
  label: "Details",
  isRequired: true,
  renderLabel: false,
  fields: [
    {
      type: InputType.DRIVER_DYNAMIC,
      name: "driver",
      label: "Driver *",
      rules: [getValidation(REQUIRED, "name")],
      placeholder: "Event Log ID",
      hasFeedback: true,
      title: "Driver",
      span: 12,
      width: "95%",
    },

    {
      type: InputType.DRIVER_DYNAMIC,
      name: "co_driver",
      rules: [getValidation(REQUIRED, "name")],

      placeholder: "Co Driver",
      hasFeedback: true,
      span: 12,
      width: "100%",
      title: "Co Driver",
    },

    {
      type: InputType.CARRIER_DYNAMIC,
      name: "carrier",
      title: "Carrier",
      // rules: [getValidation(REQUIRED, "Status")],
      placeholder: "Select Carrier",
      // options: carrierData.status,
      hasFeedback: true,
      span: 12,
      width: "95%",
    },
    {
      type: InputType.VEHICLE_DYNAMIC,
      name: "vehicle",
      title: "Vehicle",
      rules: [getValidation(REQUIRED, "Status")],
      placeholder: "Select Vehicle",
      // options: carrierData.status,
      hasFeedback: true,
      span: 12,
      width: "100%",
    },
    {
      type: InputType.SELECT_V2,
      name: "vehicle",
      title: "Vehicle",
      rules: [getValidation(REQUIRED, "Status")],
      placeholder: "Select Vehicle",
      // options: carrierData.status,
      hasFeedback: true,
      span: 12,
      width: "95%",
      options: [
        {
          key: 0,
          value: "Vehicle 01",
        },
        {
          key: 1,
          value: "Vehicle 02",
        },
      ],
    },
    {
      type: InputType.SELECT_V2,
      name: "eld",
      title: "Eld",
      rules: [getValidation(REQUIRED, "Status")],
      placeholder: "Select Eld",
      // options: carrierData.status,
      hasFeedback: true,
      span: 12,
      width: "100%",
      options: [
        {
          key: 0,
          value: "Eld 01",
        },
        {
          key: 1,
          value: "Eld 02",
        },
      ],
    },
    {
      type: InputType.TEXT_V2,
      name: "odometer",
      // rules: [validate("", ALPHABETICAL)],
      placeholder: "Enter Odometer",
      hasFeedback: true,
      span: 12,
      width: "95%",
      title: "Odometer",
    },
    {
      type: InputType.TEXT_V2,
      name: "eh",
      // rules: [validate("", ALPHABETICAL)],
      placeholder: "Enter EH",
      hasFeedback: true,
      span: 12,
      width: "100%",
      title: "EH",
    },
    {
      type: InputType.TEXT_V2,
      name: "location",
      // rules: [validate("", ALPHABETICAL)],
      placeholder: "Enter Location",
      hasFeedback: true,
      span: 12,
      width: "95%",
      title: "Location",
    },
    {
      type: InputType.TEXT_V2,
      name: "note",
      // rules: [validate("", ALPHABETICAL)],
      placeholder: "Enter Note",
      hasFeedback: true,
      span: 12,
      width: "100%",
      title: "Note",
    },
    {
      type: InputType.TEXT_V2,
      name: "lat_ocation",
      // rules: [validate("", ALPHABETICAL)],
      placeholder: "Enter Lat Location",
      hasFeedback: true,
      span: 12,
      width: "95%",
      title: "Lat Location",
    },
    {
      type: InputType.TEXT_V2,
      name: "lng_location",
      // rules: [validate("", ALPHABETICAL)],
      placeholder: "Enter Lng Location",
      hasFeedback: true,
      span: 12,
      width: "100%",
      title: "Lng Location",
    },
  ],
};
