import { InputType } from "../../../../constants/inputs";
import { generateArrayOfYears } from "../../../../hooks/utils";
import {
  VALIDATION_RULES,
  validate,
  VALIDATION_TYPE,
  getValidation,
} from "../../../../utils/validation";
import {
  carrierStatusOptions,
  CarrierField,
  carrierCheckboxGroup,
  carrierData,
  VehicleField,
} from "../constant";
import { EVENT_TYPE } from "./log-contant";

const { ALPHABETICAL, REQUIRED, MIN, MAX, NUMERIC, PASSWORD, EMAIL, NAME } =
  VALIDATION_TYPE;

export const NameDriverFields = {
  type: InputType.MULTI,
  label: "Details",
  isRequired: true,
  renderLabel: false,
  fields: [
    {
      type: InputType.TIME_PICKER_LOG,
      name: "start_time",
      rules: [getValidation(REQUIRED, "name")],

      placeholder: "Time",
      hasFeedback: true,
      span: 12,
      width: "95%",
      title: "Start Time",
    },

    {
      type: InputType.TIME_PICKER_LOG,
      name: "end_time",
      rules: [getValidation(REQUIRED, "name")],

      placeholder: "End Time",
      hasFeedback: true,
      span: 12,
      width: "100%",
      title: "End Time",
    },

    {
      type: InputType.SELECT_V2,
      name: "event",
      title: "Event",
      // rules: [getValidation(REQUIRED, "Status")],
      placeholder: "Select Event",
      // options: carrierData.status,
      hasFeedback: true,
      span: 12,
      width: "95%",
      options: EVENT_TYPE,
    },
    {
      type: InputType.SELECT_V2,
      name: "origin",
      title: "Origin",
      rules: [getValidation(REQUIRED, "Status")],
      placeholder: "Select Origin",
      // options: carrierData.status,
      hasFeedback: true,
      span: 12,
      width: "100%",
      options: [
        {
          key: 0,
          value: "Origin",
        },
        {
          key: 1,
          value: "Driver",
        },
      ],
    },
    {
      type: InputType.SELECT_V2,
      name: "vehicle",
      title: "Vehicle",
      rules: [getValidation(REQUIRED, "Status")],
      placeholder: "Select Vehicle",
      // options: carrierData.status,
      hasFeedback: true,
      span: 12,
      width: "95%",
      options: [
        {
          key: 0,
          value: "Vehicle 01",
        },
        {
          key: 1,
          value: "Vehicle 02",
        },
      ],
    },
    {
      type: InputType.SELECT_V2,
      name: "eld",
      title: "Eld",
      rules: [getValidation(REQUIRED, "Status")],
      placeholder: "Select Eld",
      // options: carrierData.status,
      hasFeedback: true,
      span: 12,
      width: "100%",
      options: [
        {
          key: 0,
          value: "Eld 01",
        },
        {
          key: 1,
          value: "Eld 02",
        },
      ],
    },
    {
      type: InputType.TEXT_V2,
      name: "odometer",
      // rules: [validate("", ALPHABETICAL)],
      placeholder: "Enter Odometer",
      hasFeedback: true,
      span: 12,
      width: "95%",
      title: "Odometer",
    },
    {
      type: InputType.TEXT_V2,
      name: "eh",
      // rules: [validate("", ALPHABETICAL)],
      placeholder: "Enter EH",
      hasFeedback: true,
      span: 12,
      width: "100%",
      title: "EH",
    },
    {
      type: InputType.TEXT_V2,
      name: "identificator",
      // rules: [validate("", ALPHABETICAL)],
      placeholder: "ID",
      hasFeedback: true,
      span: 12,
      width: "95%",
      title: "ID",
    },
    {
      type: InputType.TEXT_V2,
      name: "note",
      // rules: [validate("", ALPHABETICAL)],
      placeholder: "Enter Note",
      hasFeedback: true,
      span: 12,
      width: "100%",
      title: "Note",
    },
    {
      type: InputType.TEXT_V2,
      name: "location",
      // rules: [validate("", ALPHABETICAL)],
      placeholder: "Location",
      hasFeedback: true,
      span: 24,
      width: "100%",
      title: "Location",
    },
    {
      type: InputType.TEXT_V2,
      name: "lat_ocation",
      // rules: [validate("", ALPHABETICAL)],
      placeholder: "Enter Lat Location",
      hasFeedback: true,
      span: 12,
      width: "95%",
      title: "Lat Location",
    },
    {
      type: InputType.TEXT_V2,
      name: "lng_location",
      // rules: [validate("", ALPHABETICAL)],
      placeholder: "Enter Lng Location",
      hasFeedback: true,
      span: 12,
      width: "100%",
      title: "Lng Location",
    },
    {
      type: InputType.DRIVER_DYNAMIC,
      name: "co_driver",
      // rules: [validate("", ALPHABETICAL)],
      placeholder: "Select CO Driver",
      hasFeedback: true,
      span: 24,
      width: "100%",
      title: "Co-Driver",
    },
    {
      type: InputType.TEXT_V2,
      name: "document",
      // rules: [validate("", ALPHABETICAL)],
      placeholder: "Enter Shipping Document",
      hasFeedback: true,
      span: 12,
      width: "95%",
      title: "Shipping Document",
    },
    {
      type: InputType.TEXT_V2,
      name: "trailer",
      // rules: [validate("", ALPHABETICAL)],
      placeholder: "Enter Trailer",
      hasFeedback: true,
      span: 12,
      width: "100%",
      title: "Trailer",
    },
  ],
};
